### ISSUE TITLE
User logout time saved only if logout button is clicked

### ISSUE THREAD

**Issue by serena-zhu** [serena-zhu/Matcha#108] opened 2018-05-18 02:33 UTC
User appears online if they just close the window

**Comment by jchung05** [comment] 2018-05-18 10:51
If a user closes their window technically there should be a forced logout due to expiration of session, but since sessions are set to permanent and expire in 31 days this is not a bug and is intentional.

If we decide to implement a solid "Keep user logged in" function which will alternate between expiring sessions and permanent ones, we will need to add a window.onunload(); function that persists in every page of our site to do an AJAX request to log out. If we decide not to do this, then this is not an issue. Closing until reopened for further discussion.

**Closed by jchung05** 2018-05-18 10:51 UTC
Labels: bug, wontfix
